server:
  port: 8093
  servlet:
    context-path: /easyschool/academic

spring:
  application:
    name: es-academic-ms
  profiles:
    active:
    - dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka/


